#!/bin/bash

set -eu

if [[ -n "${1-}" ]]; then
  RUST_VERSION="$1"
else
  echo "Error: No Rust version set."
  echo
  echo "Usage:"
  echo "  ./build_and_test <Rust version> <build version>"
  echo "  ./build_and_test 1.29.1 0.0.1"
  exit 1
fi

if [[ -n "${2-}" ]]; then
  BUILD_VERSION="$2"
else
  echo "Error: No build version set."
  echo
  echo "Usage:"
  echo "  ./build_and_test <Rust version> <build version>"
  echo "  ./build_and_test 1.29.1 0.0.1"
  exit 1
fi

export TARGET_TRIPLE=x86_64-unknown-linux-musl

echo "Creating build machine."
vagrant up cross
vagrant ssh cross -c "which cross || cargo install cross"

rm -rf build
mkdir build

echo "Building Rust extension."
vagrant ssh cross -c "/rust_lib/build_in_vm $RUST_VERSION $TARGET_TRIPLE"

rm -f elixir_app/elixir_package/c_src/libelixir_package_extension.a
cp rust_lib/target/$TARGET_TRIPLE/release/libelixir_package_extension.a elixir_app/elixir_package/c_src

echo "Building Elixir app release."
export PROJECT_NAME=elixir_app
(
  cd elixir_app
  docker build --build-arg BUILD_VERSION=$BUILD_VERSION -t alpine-elixir-build-test:build .
  docker run -e BUILD_VERSION=$BUILD_VERSION -it --rm alpine-elixir-build-test:build ash
)
