#!/bin/bash

set -eu

if [[ -n "${1-}" ]]; then
  RUST_VERSION="$1"
else
  echo "Error: No Rust version set."
  echo
  echo "Usage:"
  echo "  ./build_and_test <Rust version>"
  echo "  ./build_and_test 1.29.1"
  exit 1
fi

TARGET_TRIPLE=x86_64-unknown-linux-musl

echo
echo "Creating build machine."
(
  cd rust_lib
  vagrant up cross
)

echo
echo "Building Rust extension."
(
  cd rust_lib
  vagrant ssh cross -c "/rust_lib/build_in_vm $RUST_VERSION $TARGET_TRIPLE"
)

rm -f elixir_app/elixir_package/c_src/libelixir_package_extension.a
cp rust_lib/target/$TARGET_TRIPLE/release/libelixir_package_extension.a elixir_app/elixir_package/c_src
