#!/bin/bash

set -eu

if [[ -n "$1" ]]; then
  RUST_VERSION="$1"
else
  echo "Error: No Rust version set."
  exit 1
fi

if [[ -n "$2" ]]; then
  TARGET_TRIPLE="$2"
else
  echo "Error: No TARGET_TRIPLE set."
  exit 1
fi

cd /rust_lib
# Install cross if not installed
which cross || cargo install cross

# Install specified Rust version
rustup override set $RUST_VERSION
# Add specified target
rustup target install $TARGET_TRIPLE
# Musl build requires this flag for staticlibs
export RUSTFLAGS='-C target-feature=-crt-static'
# Build staticlib through cross
cross build --target=$TARGET_TRIPLE --release --verbose
