[package]
name = "elixir_package_extension"
version = "0.1.0"
authors = ["Tom de Bruijn <tom@tomdebruijn.com>"]

[lib]
name = "elixir_package_extension"
crate_type = ["staticlib"]

[dependencies]
libc="0.2.40"
